services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/root/ssl
    # environment: 
    #   - FLASK_SERVER_ADDR=backend:5328  
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ui
      - api

  ui:
    image: 640550388417.dkr.ecr.us-west-2.amazonaws.com/pepe-silvia-ui:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000

  api:
    image: 640550388417.dkr.ecr.us-west-2.amazonaws.com/pepe-silvia-api:latest
    restart: always
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - 5328:5328
    environment:
      - FLASK_SERVER_PORT=5328
    volumes:
     - type: bind
       source: ./.aws
       target: /pepe-silvia/.aws
